#include "sms/sports_service.hpp"
#include <algorithm>
#include <fstream>
#include <map>
#include <cctype>
#include <sstream>
namespace sms {
bool SportsService::validate_member(const Member&m,std::string&e) const {if(m.id.empty()){e="member id is required";return false;} if(m.first_name.empty()||m.last_name.empty()){e="member name is required";return false;} if(!m.team_code.empty()&&!teams_.find(m.team_code)){e="team code does not exist";return false;} return true;}
bool SportsService::validate_team(const Team&t,std::string&e) const {if(t.code.empty()){e="team code is required";return false;} if(t.name.empty()){e="team name is required";return false;} if(t.sport.empty()){e="sport is required";return false;} return true;}
bool SportsService::validate_match(const Match&m,std::string&e) const {if(m.id.empty()){e="match id is required";return false;} if(m.home_score<0||m.away_score<0){e="scores cannot be negative";return false;} if(m.home_team_code==m.away_team_code){e="home and away teams must differ";return false;} auto h=teams_.find(m.home_team_code),a=teams_.find(m.away_team_code); if(!h||!a){e="both teams must exist";return false;} if(h->sport!=m.sport||a->sport!=m.sport){e="match sport must agree with both teams";return false;} return true;}
bool SportsService::validate_performance(const Performance&p,std::string&e) const {if(!performances_){e="performance repository is not configured";return false;} if(p.id.empty()){e="performance id is required";return false;} auto member=members_.find(p.member_id);auto match=matches_.find(p.match_id);if(!member||!match){e="member and match must exist";return false;} if(match->sport!=p.sport){e="performance sport must match the match";return false;} if(member->team_code!=match->home_team_code&&member->team_code!=match->away_team_code){e="member team did not participate in the match";return false;} if(p.primary<0||p.secondary<0||p.tertiary<0){e="statistics cannot be negative";return false;} return true;}
bool SportsService::add_member(Member m,std::string&e){if(!validate_member(m,e))return false;if(!members_.add(std::move(m))){e="member id already exists";return false;}e.clear();return true;}
bool SportsService::update_member(Member m,std::string&e){if(!validate_member(m,e))return false;if(!members_.update(m)){e="member not found";return false;}e.clear();return true;}
bool SportsService::remove_member(const std::string&id,std::string&e){if(performances_)for(const auto&p:performances_->list())if(p.member_id==id){e="member is referenced by a performance record";return false;}if(!members_.remove(id)){e="member not found";return false;}e.clear();return true;}
bool SportsService::add_team(Team t,std::string&e){if(!validate_team(t,e))return false;if(!teams_.add(std::move(t))){e="team code already exists";return false;}e.clear();return true;}
bool SportsService::update_team(Team t,std::string&e){if(!validate_team(t,e))return false;auto old=teams_.find(t.code);if(!old){e="team not found";return false;} if(old->sport!=t.sport){for(auto&m:members_.list())if(m.team_code==t.code){e="cannot change sport while members are assigned";return false;}for(auto&m:matches_.list())if(m.home_team_code==t.code||m.away_team_code==t.code){e="cannot change sport while matches reference team";return false;}} if(!teams_.update(t)){e="update failed";return false;}e.clear();return true;}
bool SportsService::add_match(Match m,std::string&e){if(!validate_match(m,e))return false;if(!matches_.add(std::move(m))){e="match id already exists";return false;}e.clear();return true;}
bool SportsService::update_match(Match m,std::string&e){if(!validate_match(m,e))return false;if(!matches_.update(m)){e="match not found";return false;}e.clear();return true;}
bool SportsService::remove_match(const std::string&id,std::string&e){if(performances_)for(const auto&p:performances_->list())if(p.match_id==id){e="match is referenced by a performance record";return false;}if(!matches_.remove(id)){e="match not found";return false;}e.clear();return true;}
bool SportsService::add_performance(Performance p,std::string&e){if(!validate_performance(p,e))return false;if(!performances_->add(std::move(p))){e="performance id already exists";return false;}e.clear();return true;}
bool SportsService::update_performance(Performance p,std::string&e){if(!validate_performance(p,e))return false;if(!performances_->update(p)){e="performance not found";return false;}e.clear();return true;}
bool SportsService::remove_performance(const std::string&id,std::string&e){if(!performances_){e="performance repository is not configured";return false;}if(!performances_->remove(id)){e="performance not found";return false;}e.clear();return true;}
bool SportsService::remove_team(const std::string&c,std::string&e){for(auto&m:members_.list())if(m.team_code==c){e="team has assigned members";return false;}for(auto&m:matches_.list())if(m.home_team_code==c||m.away_team_code==c){e="team is referenced by a match";return false;}if(!teams_.remove(c)){e="team not found";return false;}e.clear();return true;}
int SportsService::performance_score(const Performance&p) const {if(p.sport=="soccer")return p.primary*5+p.secondary*3+p.tertiary; if(p.sport=="netball")return p.primary*2+p.secondary*3+p.tertiary*4; if(p.sport=="track"||p.sport=="track and field")return p.primary*10+p.secondary*7+p.tertiary*5; return p.primary+p.secondary+p.tertiary;}
std::optional<MvpResult> SportsService::mvp_for_sport(const std::string&sport) const {if(!performances_)return std::nullopt;std::map<std::string,int> totals;for(auto&p:performances_->list())if(p.sport==sport)totals[p.member_id]+=performance_score(p);std::optional<MvpResult> best;for(auto&[id,score]:totals){auto m=members_.find(id);if(m&&(!best||score>best->score||(score==best->score&&id<best->member.id)))best=MvpResult{*m,score};}return best;}
bool SportsService::write_mvp_file(const std::filesystem::path&path,std::string&e) const {std::ofstream out(path,std::ios::trunc);if(!out){e="unable to open MVP file";return false;}for(auto sport:{std::string("soccer"),std::string("netball"),std::string("track")}){auto result=mvp_for_sport(sport);out<<sport<<": ";if(result)out<<result->member.first_name<<' '<<result->member.last_name<<" ("<<result->member.id<<") score="<<result->score;else out<<"No qualifying statistics";out<<'\n';}e.clear();return static_cast<bool>(out);}
}

namespace {
std::string lower_copy(std::string value){for(char& c:value)c=static_cast<char>(std::tolower(static_cast<unsigned char>(c)));return value;}
}
namespace sms {
std::vector<Member> SportsService::search_members(const std::string&q) const {std::vector<Member> out;auto needle=lower_copy(q);for(auto&m:members_.list()){auto hay=lower_copy(m.id+" "+m.first_name+" "+m.last_name+" "+m.team_code);if(needle.empty()||hay.find(needle)!=std::string::npos)out.push_back(m);}return out;}
std::vector<TeamSummary> SportsService::team_summaries(const std::string&sport) const {std::vector<TeamSummary> out;for(auto&t:teams_.list()){if(!sport.empty()&&t.sport!=sport)continue;TeamSummary s{t,0,0,0,0,0,0,0};for(auto&m:members_.list())if(m.team_code==t.code)++s.members;for(auto&match:matches_.list()){bool home=match.home_team_code==t.code,away=match.away_team_code==t.code;if(!home&&!away)continue;++s.matches_played;int pf=home?match.home_score:match.away_score,pa=home?match.away_score:match.home_score;s.points_for+=pf;s.points_against+=pa;if(pf>pa)++s.wins;else if(pf==pa)++s.draws;else ++s.losses;}out.push_back(s);}return out;}
bool SportsService::write_report_file(const std::filesystem::path&path,std::string&e) const {std::ofstream out(path,std::ios::trunc);if(!out){e="unable to open report file";return false;}out<<"Sports Management System Report\n\n";for(auto&s:team_summaries()){out<<s.team.code<<" | "<<s.team.name<<" | "<<s.team.sport<<" | members="<<s.members<<" | played="<<s.matches_played<<" | W-D-L="<<s.wins<<'-'<<s.draws<<'-'<<s.losses<<" | PF="<<s.points_for<<" | PA="<<s.points_against<<'\n';}auto issues=audit_data_quality();out<<"\nData quality issues: "<<issues.size()<<'\n';for(auto&i:issues)out<<"- "<<i<<'\n';e.clear();return static_cast<bool>(out);}
std::vector<std::string> SportsService::audit_data_quality() const {std::vector<std::string> issues;for(auto&m:members_.list())if(!m.team_code.empty()&&!teams_.find(m.team_code))issues.push_back("member "+m.id+" references missing team "+m.team_code);for(auto&match:matches_.list()){auto h=teams_.find(match.home_team_code),a=teams_.find(match.away_team_code);if(!h||!a)issues.push_back("match "+match.id+" references a missing team");else if(h->sport!=match.sport||a->sport!=match.sport)issues.push_back("match "+match.id+" has inconsistent sport");if(match.home_score<0||match.away_score<0)issues.push_back("match "+match.id+" has a negative score");}if(performances_)for(auto&p:performances_->list()){if(!members_.find(p.member_id))issues.push_back("performance "+p.id+" references missing member "+p.member_id);if(!matches_.find(p.match_id))issues.push_back("performance "+p.id+" references missing match "+p.match_id);}return issues;}
}